name: Build

on: [push]

env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    name: Run Build on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Build .NET solution
      run: |
        dotnet --version
        dotnet build ./src/dotnet-microservices.sln --configuration Release

    - name: Build the deliveries Docker image
      run: docker build . --file src/services/deliveries/Dockerfile --tag deliveries:${{ github.sha }}

    - name: Build the ordering Docker image
      run: docker build . --file src/services/ordering/Dockerfile --tag ordering:${{ github.sha }}

    - name: Validate docker-compose-ubuntu
      run: |
        docker --version
        docker-compose --version
        cd compose
        chmod 0700 ./_scripts/apigateway-gen-certificate.sh
        bash ./_scripts/apigateway-gen-certificate.sh
        docker-compose config

  sonarCloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}