name: Docker Image CI

on: [push, pull_request]

jobs:

  build:
    name: Run Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.401
    - name: Build project in .NET
      run: dotnet build ./src/dotnet-microservices.sln --configuration Release
    - name: Build with cake
      uses: gep13/cake-actions/task@master
    - name: Build the apigateway Docker image
      run: docker build . --file src/services/apigateway/Dockerfile --tag apigateway:$(date +%s)
    - name: Build the deliveries Docker image
      run: docker build . --file src/services/deliveries/Dockerfile --tag deliveries:$(date +%s)
    - name: Build the ordering Docker image
      run: docker build . --file src/services/ordering/Dockerfile --tag ordering:$(date +%s)
